#!/usr/bin/env python3
"""Investigate exact driller-name phrase reuse and location concentration.

Run after profile_raw_lithology.py and compare_bonded_descriptions.py. Only derived files under
04_analysis/raw_lithology_profile are written.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.colors import to_rgba
from matplotlib.ticker import PercentFormatter
import numpy as np
import pandas as pd
from pyproj import Transformer
from driller_analysis_common import selected_drillers, well_units
from township_location_qc import audit_locations


ROOT = Path(__file__).resolve().parents[1]
K = 5
EXAMPLE_NAME = "BRANDON BROWN"


def nearest_indices(frame: pd.DataFrame) -> np.ndarray:
    """Return five nearest other well units, allowing coincident coordinates."""
    lon = frame.longitude.to_numpy(dtype=float)
    lat = frame.latitude.to_numpy(dtype=float)
    # OWRD's queried geometry is WGS84; all points lie in UTM zone 11N.
    x, y = Transformer.from_crs("EPSG:4326", "EPSG:32611", always_xy=True).transform(lon, lat)
    xy = np.column_stack([x, y])
    squared = ((xy[:, None, :] - xy[None, :, :]) ** 2).sum(axis=2)
    np.fill_diagonal(squared, np.inf)
    # Stable order makes exact-distance ties reproducible by well-key row order.
    return np.argsort(squared, axis=1, kind="stable")[:, :K]


def neighbor_stats(frame: pd.DataFrame) -> pd.DataFrame:
    """Same-name share among five nearest well units, by driller."""
    if len(frame) <= K:
        raise ValueError("Not enough mapped well units for five nearest neighbours")
    frame = frame.reset_index(drop=True)
    neighbors = nearest_indices(frame)
    names, codes = np.unique(frame.bonded_full_name.to_numpy(), return_inverse=True)
    n_by_name = np.bincount(codes, minlength=len(names))

    same_count = (codes[:, None] == codes[neighbors]).sum(axis=1)
    observed = np.bincount(codes, weights=same_count, minlength=len(names)) / (K * n_by_name)
    result = pd.DataFrame({
        "bonded_full_name": names,
        "well_units": n_by_name,
        "observed_same_name_fraction": observed,
        "driller_share_of_well_units": n_by_name / len(frame),
        "difference_percentage_points": 100 * (observed - n_by_name / len(frame)),
    })
    return result


def write_named_example(phrases: pd.DataFrame, summary: pd.DataFrame, out: Path) -> None:
    """Keep the full Brandon Brown wording example reproducible and reviewable."""
    block = phrases[phrases.bonded_full_name == EXAMPLE_NAME]
    if block.empty:
        raise ValueError(f"Expected example name absent from interval data: {EXAMPLE_NAME}")
    stats = summary.set_index("bonded_full_name").loc[EXAMPLE_NAME]
    one_report = int((block.report_count == 1).sum())
    one_interval = int(((block.report_count == 1) & (block.interval_count == 1)).sum())
    lines = [
        f"# {EXAMPLE_NAME}: exact interval descriptions",
        "",
        "This example uses the recorded driller name `BRANDON BROWN` and one selected geological report per identified well. It excludes report `565542`, whose coordinates fall outside the study area, plus linked alternative and abandonment-only reports. It does not include `BRANDON C BROWN`. The field does not establish who wrote each description.",
        "",
        f"Across **{int(stats.reports):,} identified well units** and **{int(stats.intervals):,} intervals**, this name is associated with **{len(block):,} distinct exact description strings**. **{int(stats.phrases_reused_in_2plus_reports):,}** occur in at least two wells; **{one_report:,}** occur in one well only. Of the latter, **{one_interval:,}** occur in just one interval, and **{one_report - one_interval:,}** recur within their single selected report.",
        "",
        f"These strings are not {len(block):,} rock types. Many combine material, colour, hardness, fracturing, and adjoining material; some are abbreviations, spelling variants, or construction notes. That detail is valuable source information but produces a long tail for any future classification. No descriptions are merged or assigned standardized labels here.",
        "",
        "Each table row is one exact stored `material_raw` string. The Wells column counts identified well units containing it; interval count includes repeat occurrences within a selected report. This file is regenerated by `uv run python scripts/investigate_bonded_naming_spatial.py`.",
    ]
    for title, subset in [
        ("Descriptions used in two or more wells", block[block.report_count >= 2]),
        ("Descriptions used in one well", block[block.report_count == 1]),
    ]:
        lines.extend(["", f"## {title}", "", "| Exact description | Wells | Intervals |", "|---|---:|---:|"])
        for row in subset.itertuples():
            description = row.material_raw.replace("|", "\\|").replace("`", "\\`")
            lines.append(f"| {description} | {row.report_count} | {row.interval_count} |")
    (out.parent / "BRANDON_BROWN.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def reused_phrases(intervals: pd.DataFrame, units: pd.DataFrame, cohort: pd.DataFrame,
                   out: Path) -> pd.DataFrame:
    merged = intervals.merge(units[["wl_id", "bonded_full_name"]], left_on="well_id",
                             right_on="wl_id", how="inner", validate="many_to_one")
    merged = merged[merged.bonded_full_name.isin(cohort.bonded_full_name) & merged.material_raw.str.strip().ne("")].copy()
    reports_by_name = merged.groupby("bonded_full_name").well_id.nunique()
    if set(reports_by_name.index) != set(cohort.bonded_full_name):
        raise AssertionError("Reuse profile does not cover the selected cohort")
    phrases = merged.groupby(["bonded_full_name", "material_raw"]).agg(
        interval_count=("well_id", "size"), report_count=("well_id", "nunique")
    ).reset_index()
    phrases["reused_across_wells"] = phrases.report_count.ge(2)
    phrases["name_report_count"] = phrases.bonded_full_name.map(reports_by_name)
    phrases["share_of_name_reports"] = phrases.report_count / phrases.name_report_count
    phrases = phrases.sort_values(["bonded_full_name", "report_count", "interval_count", "material_raw"], ascending=[True, False, False, True])
    phrases.to_csv(out / "bonded_reused_descriptions.csv", index=False)

    summary_rows = []
    for name, block in phrases.groupby("bonded_full_name"):
        rows = merged[merged.bonded_full_name == name]
        reused = block[block.reused_across_wells]
        repeated_text = set(reused.material_raw)
        top = block.iloc[0]
        summary_rows.append({
            "bonded_full_name": name,
            "reports": int(reports_by_name[name]),
            "intervals": len(rows),
            "distinct_exact_phrases": len(block),
            "phrases_reused_in_2plus_reports": len(reused),
            "reports_with_a_reused_phrase": rows.loc[rows.material_raw.isin(repeated_text), "well_id"].nunique(),
            "intervals_with_a_reused_phrase": int(rows.material_raw.isin(repeated_text).sum()),
            "top_phrase": top.material_raw,
            "top_phrase_reports": int(top.report_count),
            "top_phrase_intervals": int(top.interval_count),
            "top_phrase_report_share": float(top.share_of_name_reports),
        })
    summary = pd.DataFrame(summary_rows).sort_values(["reports", "bonded_full_name"], ascending=[False, True])
    summary.to_csv(out / "bonded_reuse_summary.csv", index=False)
    write_named_example(phrases, summary, out)

    return summary


def spatial(units: pd.DataFrame, cohort: pd.DataFrame, out: Path) -> tuple[pd.DataFrame, dict]:
    if units.well_key.duplicated().any():
        raise ValueError("A well appears more than once in the spatial input")
    names = cohort.bonded_full_name.tolist()
    named = units[units.location_class.isin(["A", "B"]) & units.bonded_full_name.isin(names)].sort_values("well_key").reset_index(drop=True).copy()
    named["latitude"] = pd.to_numeric(named.latitude_dec, errors="raise")
    named["longitude"] = pd.to_numeric(named.longitude_dec, errors="raise")
    primary = neighbor_stats(named)
    if set(primary.bonded_full_name) != set(names):
        raise AssertionError("Spatial analysis does not cover the selected cohort")

    # Distinct wells can still share coordinates; remove all such wells in a
    # sensitivity check without modifying their source records.
    pair_size = named.groupby(["latitude", "longitude"]).well_key.transform("size")
    unique = named[pair_size == 1].copy()
    unique_stats = neighbor_stats(unique).rename(columns={
        "well_units": "unique_coordinate_well_units",
        "observed_same_name_fraction": "unique_coordinate_observed_fraction",
        "driller_share_of_well_units": "unique_coordinate_driller_share",
        "difference_percentage_points": "unique_coordinate_difference_points",
    })
    primary = primary.merge(unique_stats, on="bonded_full_name", how="left", validate="one_to_one")
    primary.loc[primary.unique_coordinate_well_units.lt(10),
                ["unique_coordinate_observed_fraction", "unique_coordinate_driller_share", "unique_coordinate_difference_points"]] = np.nan
    primary = primary.sort_values(["well_units", "bonded_full_name"], ascending=[False, True])
    primary.to_csv(out / "bonded_spatial_summary.csv", index=False)

    fig, ax = plt.subplots(figsize=(10, max(7, 0.42 * len(primary) + 1.5)))
    shown = primary.sort_values("observed_same_name_fraction")
    ax.barh(shown.bonded_full_name, shown.observed_same_name_fraction * 100, color="#376a8a",
            label="Five nearest wells by the same driller")
    ax.scatter(shown.driller_share_of_well_units * 100, shown.bonded_full_name, marker="|", s=140,
               color="#dfaa35", label="This driller's share of all wells", zorder=3)
    ax.set(xlabel="Spatial Correlation (percentage of five nearest wells by the same driller)",
           title="Spatial correlation by driller")
    ax.grid(axis="x", alpha=0.2)
    ax.legend(loc="lower right")
    fig.tight_layout()
    fig.savefig(out / "bonded_neighbor_fraction.png", dpi=170)
    plt.close(fig)

    ab_dice = pd.read_csv(out / "bonded_ab_within_between_similarity.csv")
    relationship = primary.merge(ab_dice[["bonded_full_name", "lithology_wells", "within_dice"]],
                                 on="bonded_full_name", validate="one_to_one")
    if len(relationship) != len(primary) or not relationship.well_units.eq(relationship.lithology_wells).all():
        raise ValueError("Figure 5 Dice and spatial scores must use the same A/B wells")
    relationship = relationship.rename(columns={"within_dice": "ab_within_dice"})
    relationship.to_csv(out / "bonded_spatial_vocabulary_relationship.csv", index=False)
    x = relationship.ab_within_dice * 100
    y = relationship.observed_same_name_fraction * 100
    pearson = float(x.corr(y))
    spearman = float(x.rank().corr(y.rank()))
    fig, ax = plt.subplots(figsize=(11, 7.5))
    marker_sizes = 4 * (45 + 2 * relationship.well_units)
    ax.scatter(x, y, s=marker_sizes, facecolors=to_rgba("#376a8a", 0.3),
               edgecolors="black", linewidths=0.8, zorder=3)
    ax.set(xlabel="Lithology interpretation consistency",
           ylabel="Spatial Correlation (percentage of five nearest wells by the same driller)",
           title="Interpretation consistency and spatial correlation")
    ax.set_xlim(0, x.max() + 7)
    ax.set_ylim(0, max(100, y.max() * 1.08))
    ax.set_yticks(np.arange(0, 101, 20))
    ax.xaxis.set_major_formatter(PercentFormatter(xmax=100, decimals=0))
    ax.grid(alpha=0.18)
    ax.text(0.02, 0.98, f"{len(relationship)} drillers",
            transform=ax.transAxes, ha="left", va="top", fontsize=9)
    legend_counts = [10, 44, 112, 176]
    legend_handles = [
        ax.scatter([], [], s=4 * (45 + 2 * count),
                   facecolors=to_rgba("#376a8a", 0.3), edgecolors="black",
                   linewidths=0.8,
                   label=f"{count} wells ({count / len(named):.1%})")
        for count in legend_counts
    ]
    ax.legend(handles=legend_handles, title=f"A/B well count (share of {len(named)})",
              loc="upper right", framealpha=0.95, labelspacing=4.6,
              handletextpad=4, borderpad=2.2, fontsize=8)
    # Fixed callout positions keep the dense middle group readable.
    label_positions = {
        "J TRENT CASTNER": (21.5, 85),
        "PETER LARSEN": (8.3, 55),
        "CHAD N GREGORY": (17.2, 49),
        "GARRY ZOLLMAN": (28.0, 40),
        "PAUL SMITH": (10.2, 36),
        "BRANDON BROWN": (19.7, 35),
        "TERRENCE JACQUES": (10.5, 41),
        "BRANDON C BROWN": (10.0, 28),
        "CHAD GREGORY": (11.0, 16),
        "BEN DREYER": (4.0, 26),
        "PATRICK WALLACE": (15.4, 12),
        "CHAD COURTNEY": (22.2, 9),
        "LARRY BURD": (23.0, 25),
        "EDWIN BROWN": (37.4, 8),
    }
    for row, size in zip(relationship.itertuples(), marker_sizes):
        point = (row.ab_within_dice * 100, row.observed_same_name_fraction * 100)
        label = label_positions.get(row.bonded_full_name, (point[0] + 2, point[1] + 4))
        ax.annotate(row.bonded_full_name, xy=point, xytext=label,
                    ha="center", va="center", fontsize=8, zorder=4,
                    arrowprops={"arrowstyle": "->", "color": "#555555",
                                "lw": 0.8, "shrinkA": 3, "shrinkB": np.sqrt(size) / 2})
    fig.tight_layout()
    fig.savefig(out / "bonded_spatial_vocabulary_relationship.png", dpi=190)
    plt.close(fig)

    meta = {
        "selected_ab_wells": len(named),
        "selected_drillers": len(primary),
        "selected_ab_wells_at_repeated_coordinates": int((pair_size > 1).sum()),
        "unique_coordinate_pool": len(unique),
        "nearest_neighbors": K,
        "crs_for_distances": "EPSG:32611",
        "relationship_pearson": pearson,
        "relationship_spearman": spearman,
    }
    (out / "bonded_investigation_summary.json").write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")
    return primary, meta


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    args = parser.parse_args()
    root = args.root.resolve()
    out = root / "04_analysis/raw_lithology_profile/artifacts"
    out.mkdir(parents=True, exist_ok=True)
    wells = pd.read_csv(root / "01_raw/owrd/wells_raw.csv", dtype=str, keep_default_na=False)
    intervals = pd.read_csv(root / "03_processed/lithology/lithology_all_raw.csv", dtype=str, keep_default_na=False)
    audit, _, _, _ = audit_locations(root, wells)
    units, _ = well_units(wells, intervals, audit)
    cohort = selected_drillers(units)
    names = reused_phrases(intervals, units, cohort, out)
    space, meta = spatial(units, cohort, out)
    print(f"Reuse profiles: {len(names)} names; spatial profiles: {len(space)} names")
    print(json.dumps(meta, indent=2))


if __name__ == "__main__":
    main()
